version: "3"
services:
    app:
      build: .
      container_name: app
      ports:
        - 8080:8080
      depends_on:
        - db
      environment:
        - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
        - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    db:
      image: 'postgres:13.1-alpine'
      container_name: db
      ports:
        - 5433:5432
      environment:
        - POSTGRES_USER=${POSTGRESQL_USERNAME}
        - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRES_DB=${POSTGRESQL_DB_NAME}
      volumes:
        - private_db_volume:/var/lib/postgresql/data
volumes:
    private_db_volume:
